#!/bin/bash

# Install MySQL server
echo >&2 'Installing and configuring MySQL Server'
sudo apt-get -qqy install mysql-server mysql-client-core-8.0

# Now, lock down MySQL server
# We don't set a root password
# We make the default user the same as the current user, with a password
#   of the username (so if the current user is fred, so is the password)

echo >&2 "Locking down MySQL server and giving $USER all privileges, with
a passsword of $USER"
sudo mysql -uroot <<-EOF
# Remove anonymous users
DELETE FROM mysql.user WHERE User='';
# Remove remote root
DELETE FROM mysql.user WHERE User='root' AND Host NOT in ('localhost', '127.0.0.1', '::1');
# Drop test database
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR db='test\_%';
# Set up d101dev user
CREATE USER IF NOT EXISTS '$USER'@'localhost' IDENTIFIED BY '$USER';
GRANT ALL PRIVILEGES ON *.* TO '$USER'@'localhost' WITH GRANT OPTION;
# Allow remote access
CREATE USER IF NOT EXISTS '$USER'@'%' IDENTIFIED BY '$USER';
GRANT ALL PRIVILEGES ON *.* TO '$USER'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
EOF

# Create ~/.my.cnf if it doesn't exist
if [ ! -f ~/.my.cnf ] ; then
    echo >&2 'Creating ~/.my.cnf file'
    cat > ~/.my.cnf <<-EOF
[client]
user=$USER
password=$USER
EOF

else
    echo >&2 '~/.my.cnf exists; not changed.'
fi

echo >&2 'Installing MySQL development'
sudo apt-get -qqy install libmysqlclient-dev
