#!/bin/bash
. setup

# Install PHP
sayit 'Installing PHP'
install php libapache2-mod-php php-mysql 
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/internal/skip-preseed boolean true"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-install boolean true"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-password-confirm password d101dev"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password d101dev"
sayit 'Installing phpmyadmin'
install phpmyadmin
