#!/bin/bash

# Install PHP
echo &2 'Installing PHP'
sudo apt-get -qqv install php libapache2-mod-php php-mysql 
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/internal/skip-preseed boolean true"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/dbconfig-sudo apt-get -qqv install boolean true"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/app-password-confirm password d101dev"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/admin-pass password d101dev"
sudo debconf-set-selections <<< "phpmyadmin phpmyadmin/mysql/app-pass password d101dev"
echo &2 'Installing phpmyadmin'
sudo apt-get -qqv install phpmyadmin
