#!/bin/bash

dir=$HOME/src/tmstats

if [ ! -f ${dir}/tmglobals.py ] ; then
    echo >&2 "You MUST clone TMSTATS from YOUR fork on GitHub"
    echo >&2 "The command is:"
    echo >&2 ""
    echo >&2 "  git clone git@github.com:USERNAME/tmstats.git"
    echo >&2 ""
    echo >&2 "with your GitHub username instead of USERNAME"
    exit 1
else
    echo >&2 'Updating code from GitHub'
    (cd ${dir};git pull)
fi


# Now, create the subdirectories we need and pull archives and pins from the server
cd ${dir}
mkdir work 2>/dev/null
mkdir archives 2>/dev/null
mkdir cursors 2>/dev/null
mkdir pins 2>/dev/null
mkdir workingalignment 2>/dev/null
rsync -vtzrL d101dev@d101tm.org:~d101tm/src/tmstats/archives/ archives/
rsync -vtzrL d101dev@d101tm.org:~d101tm/src/tmstats/pins/ pins/
scp d101dev@d101tm.org:~d101tm/src/tmstats/tmstats.ini .
scp d101dev@d101tm.org:~d101tm/src/tmstats/googleoauth2key.json .

# Finally, update the config file to reflect local information
sed -i tmstats.ini -e "s,/home/d101tm,$HOME," \
	-e 's,^copydir:.*,copydir: /var/www/html/files,' \
	-e 's,^reportsdir:.*,reportsdir: /var/www/html/files/reports/,' \
	-e 's,^wpdir:.*,wpdir: /var/www/html,' \
	-e "s,^dbuser:.*,dbuser: $USER," \
	-e "s,^dbpass:.*,dbpass: $USER," \
	-e "s,^dbhost:.*,dbpass: localhost," \
