#!/bin/bash
. setup

# Install phpmyadmin 4.8.5 (per https://devanswers.co/manually-upgrade-phpmyadmin/)

# Make sure we don't already have a late enough version

phpver=$(apt-cache show phpmyadmin | grep Version: | sed -e 's/.*://' -e 's/-.*//')

[[ $phpver < '4.8.5' ]] || exit

sayit "Updating PHP from version $phpver to version 4.8.5"
curl https://files.phpmyadmin.net/phpMyAdmin/4.8.5/phpMyAdmin-4.8.5-all-languages.tar.gz | sudo tar xz
sudo mv phpMyAdmin-4.8.5-all-languages/ phpmyadmin
sudo rm -rf /usr/share/phpmyadmin
sudo mv phpmyadmin/ /usr/share/phpmyadmin
sudo sed -i /usr/share/phpmyadmin/libraries/vendor_config.php -e "s'./tmp/'/var/lib/phpmyadmin/tmp/'" -e "s@define('CONFIG_DIR', ''@define('CONFIG_DIR', '/etc/phpmyadmin/'@"
